spring:
  data:
    elasticsearch:
      cluster-nodes: 10.0.57.253:9300
      cluster-name: es_test
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://10.0.57.253:3306/test
    driver-class-name: com.mysql.jdbc.Driver

elasticsearch:
  rest:
    client:
      cluster-nodes: 10.0.57.253:9200
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml


